apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app

spec:
  selector:
    name: postgres
    app: postgres-app
  ports:
    - port: 5432
      targetPort: 5432